# action.yml
name: 'centOS7 rpm build'
description: 'Building rpm packages for centOS7'
inputs:
  spec_file:  # id of input
    description: 'path to the spec file'
    required: true
    default: '*.spec'
outputs:
  source_rpm_path: # id of output
    description: 'path to Source RPM file'
  source_rpm_dir_path:
    description: 'path to  SRPMS directory'
  source_rpm_name:
    description: 'name of Source RPM file'
  rpm_dir_path:
    description: 'path to RPMS directory'
  rpm_content_type:
    description: 'Content-type for Upload'
runs:
  using: 'docker'
  image: 'Dockerfile'
